### ISSUE TITLE
Just some questions

### ISSUE THREAD

**Issue by testbughub** [faush01/ThemeCpData#1]
Hi!  
  
I'm in the process of exporting intro data from a show (Supernatural),  
and was planning on making a PR, but I have a few questions before I do that.  
  
1. Must the files be named 'show name (s1e1).json' or can I use the name I  
get from downloading it from Chapter API ('show name-s01e01.json')?  
  
2. Supernatural doesn't really have intros, but it gives a recap at the start  
of almost every episode. Can we still count them as intros?  
  
3. Since the recap is different every time, the intro data is different each time.  
Is there a limit to how many files I can add? (116 files so far, and I've only done 6/15 seasons so far)  
  
On a side note, I was suprised to see that there weren't more shows added.  
Maybe you could add a link to this repo somewhere in the plugin?

**Comment by faush01** [comment]
1. You can use any file names as teh actual match data are stored in the json files
2. the chormaprint audio data needs to be a match, so theme musinc etc is a good match, recaps will not work
3. you can add one for each episode as you are but it will take a long time to do the searching, this is not really how the system was intended to be used and may cuase issues with performance and delay with hundreds of into matches to do on each episode.

people did not really get behind this plugin, while it works well it does require users to do a little more work to get set up and I just dont get the feeling people want to do that. There is a link on the main forum post and originally I had a link on the plugin page but removed it when users got confused with what a git repo was.

**Comment by testbughub** [comment]
Gotcha.  
Then Supernatural doesn't really fit in here, since it doesn't have intro music.  
Thanks for the clarification!
